# Generated by Django 3.0.5 on 2020-10-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='item',
        ),
    ]
