# Generated by Django 3.0.5 on 2020-10-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201016_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='item',
        ),
    ]
