# Generated by Django 3.0.5 on 2020-10-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_comments_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
