# Generated by Django 3.0.5 on 2020-10-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201016_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cmt_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_cmt', to='auctions.Listing'),
        ),
    ]
