# Generated by Django 3.0.5 on 2020-10-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_comments_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
