# Generated by Django 3.0.5 on 2020-10-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20201020_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='item_name',
            new_name='item',
        ),
    ]
