# Generated by Django 3.0.5 on 2020-10-21 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20201020_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cmt', to=settings.AUTH_USER_MODEL),
        ),
    ]
