# Generated by Django 3.0.5 on 2020-10-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20201021_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
