# Generated by Django 3.0.5 on 2020-10-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201021_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active_listing',
            field=models.BooleanField(default=True),
        ),
    ]
