# Generated by Django 3.0.5 on 2020-10-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_listing_active_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active_listing',
            new_name='active',
        ),
    ]
