# Generated by Django 3.0.5 on 2020-10-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20201021_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
