# Generated by Django 3.0.5 on 2020-10-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
    ]
