# Generated by Django 3.0.5 on 2020-10-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
