# Generated by Django 3.0.5 on 2020-10-27 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cmt', to=settings.AUTH_USER_MODEL),
        ),
    ]
