# Generated by Django 3.0.5 on 2020-12-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20201027_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
